### PR TITLE
add es6 extractor and update esprima to 2.0.0

### PR DESCRIPTION
**Pull request by ferenc-radius**
I added a es6 extractor which is basically a wrapper around the javascript extractor

### CODE REVIEW

**Comment by arendjr** [comment]
Hi there,

Thanks for the pull request, this looks like a useful addition!

I'm a little bit concerned about the removed line from messages.expected.pot however. I don't see exactly how your code could've influenced that part, but that comment no longer being extracted does seem to indicate there's a bug somewhere. Did you look into why that comment is no longer there?

Thanks!
Arend jr.

**Comment by ferenc-radius** [comment]
Test are passing. I have a look.

**Comment by ferenc-radius** [comment]
see last commit

**Comment by arendjr** [comment]
Great, thanks!

**Pull request merged**
